== Iterator Design Pattern
:author: Oğuz Kaan YILDIZ

{author}

==== Neden kullanırız?

Iterator Pattern, temelindeki veri kümesini bilmeye gerek duymadan sıralı bir şekilde bir koleksiyon nesnesinin elemanlarına erişmekte yol almak için kullanılır.

==== UML 

[uml,file="IteratorPattern.png"]
--
@startuml

class Shape {
    - ID: int
    - Name: string
    +Shape(int,string)
    +getId() : int
    +setId(int) : void
    +getName() : String
    +setName(String) : void
    +toString(): String
}

class ShapeStorage {
    - shapes : shape[5]
    - index : int
    + AddShape(String): void
    + GetShapes(): Shape[]
}

class ShapeIterator {
    - shapes : shape[5]
    - pos : int
    + ShapeIterator(Shape[])
    + HasNext() : boolean
    + Next() : Shape
    + Remove() : void
}

class IteratorPatternDemo {
    + {static} Main(string[]) : void
}

Shape <-- ShapeIterator: shapes 0..*
Shape <-- ShapeStorage: shapes 0..*
IteratorPatternDemo <-- ShapeIterator: uses
IteratorPatternDemo <-- ShapeStorage: uses

@enduml
--

Şimdi sınıflarımızı açıklayalım..

* `**Aggregate**` - Veri kümesi içerisinde dolaşmak için bir Iterator interface’i tipinden Iterator yaratılmasını zorunlu tutan arayüzdür.
* `**Iterator**` - Veri kümesi içerisinde dolaşmanın tüm şart ve imzasını bu arayüz belirlemektedir. Yani bir enumerator(sayıcı) görevi üstlenmektedir. Uzun lafın kısası, elimizdeki veri kümesi üzerinde döngü esnasında verileri/nesneleri elde edebilmemiz için gerekli işlemleri/kontrolleri/şartları/hususları tanımlar.
* `**FruitCollection**` - Veri kümesini barındıran nesnedir. Aggregate arayüzünü uygulayarak Iterator nesnesini oluşturur.
* `**FruitIterator**` - Iterator arayüzünü uygulayan ve içerisinde iterasyon metot ve özelliklerini barındıran, yukarıda da bahsettiğimiz enumerator görevini üstlenen sınıftır.
* `**Fruit**` - Verimizin yapısını temsil eden sınıftır.
* `**Program**` - Deseni kullanarak, belirtilen şartlara göre veri kümesi içerisindeki elemanlara erişen nesnemizdir.

==== UML Diyagramının Java Ortamında Gerçeklenmesi
.Shape.java
[source, java]
----
package IteratorPattern;

public class Shape {
	private int ID;
    private String name;
     
    public Shape(int id, String name){
        this.ID = id;
        this.name = name;
    }
     
    public int getId() {
        return ID;
    }
    public void setId(int id) {
        this.ID = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
     
    @Override
    public String toString(){
        return "ID: "+ID+" Shape: "+name;
    }
}
----

.ShapeStorage.java
[source, java]
----
package IteratorPattern;

public class ShapeStorage {
	private Shape []shapes = new Shape[5];
    private int index;
     
    public void addShape(String name){
        int i = index++;
        shapes[i] = new Shape(i,name);
    }
     
    public Shape[] getShapes(){
        return shapes;
    }
}
----

.ShapeIterator.java
[source, java]
----
package IteratorPattern;

import java.util.Iterator;

public class ShapeIterator implements Iterator<Shape> {
	private Shape [] shapes;
    int pos;
     
    public ShapeIterator(Shape []shapes){
        this.shapes = shapes;
    }
    @Override
    public boolean hasNext() {
        if(pos >= shapes.length || shapes[pos] == null)
            return false;
        return true;
    }
 
    @Override
    public Shape next() {
        return shapes[pos++];
    }
 
    @Override
    public void remove() {
        if(pos <=0 )
            throw new IllegalStateException("Illegal position");
        if(shapes[pos-1] !=null){
            for (int i= pos-1; i<(shapes.length-1);i++){
                shapes[i] = shapes[i+1];
            }
            shapes[shapes.length-1] = null;
        }
    }
}
----

.IteratorPatternDemo.java
[source, java]
----
package IteratorPattern;

public class IteratorPatternDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ShapeStorage storage = new ShapeStorage();
        storage.addShape("Polygon");
        storage.addShape("Hexagon");
        storage.addShape("Circle");
        storage.addShape("Rectangle");
        storage.addShape("Square");
         
        ShapeIterator iterator = new ShapeIterator(storage.getShapes());
        while(iterator.hasNext()){
            System.out.println(iterator.next());
        }
        System.out.println("Apply removing while iterating...");
        iterator = new ShapeIterator(storage.getShapes());
        while(iterator.hasNext()){
            System.out.println(iterator.next());
            iterator.remove();
        }
	}
}

----

.Output
[source]
----
ID: 0 Shape: Polygon
ID: 1 Shape: Hexagon
ID: 2 Shape: Circle
ID: 3 Shape: Rectangle
ID: 4 Shape: Square
Apply removing while iterating...
ID: 0 Shape: Polygon
ID: 2 Shape: Circle
ID: 4 Shape: Square
----


