== Singleton Pattern
:author: Oğuz Kaan YILDIZ

{author}

==== Cihazların ID Adresleri Uygulaması(JAVA)

C# programlama dilininde Singleton Tasarım Kalıbına uygun yazılan kayıtları bir text dosyasına kaydeden uygulama.

.Device.JAVA
[source,java]
----
public class Device {
	
	private static final Device instance = new Device(); //<1>
	
	private Device() {} //<2>

	public static Device getInstance() { //<3>
		return instance;
	}
			
	public void showIDNumber() { //<4>
		System.out.println("123321");
	}
}
----
Singleton Pattern'e uygun olması için;

<1> Device sınıfı belleğe yüklendiği anda statik olan instance nesnesi oluşturulacaktır.
<2> Sınıfımızın dışarıdan çağırılması için yine statik tipte bir getInstance() methodu oluşturduk.
<3> Önceden oluşturulan Instance nesnesini geri döndürdük.
<4> Oluşturulan instance nesnesinin verisini gösterdik.

Böylece çok kanallı uygulamalar içinde tek bir nesnenin oluşmasını ve bu nesneye erişimi garanti altına alan Singleton desenini tasarlamış olduk.

.SingletonPatternDemo.java
[source,java]
----
public class SingletonPatternDemo {
	public static void main(String[] args) {
		Device obj = Device.getInstance();
		obj.showIDNumber();
	}
}
----

.Output
[source]
----
123321
----


.UML Diyagramı
[uml,file="SingletionPattern.png"]

--
@startuml

class Device {

    -{static} instance : Device
    +{static} GetInstance(): Device
    +showIDNumber(): void
}

@enduml
--
